# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tycoon/images/upload/avatar/')),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('charm', models.IntegerField(default=0)),
                ('surplus', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodeToItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='tycoon/images/upload/icon/')),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('charm', models.IntegerField(default=0)),
                ('surplus', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('explanation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=20)),
                ('is_pw_changed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='combination',
            name='item1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='combination',
            name='item2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='combination',
            name='new_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_item', to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='codetoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='cur_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Title'),
        ),
    ]
