# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='chaeyong', max_length=20)),
                ('image_f', models.ImageField(default='images/avatar/default.png', upload_to='images/avatar/')),
                ('image_b', models.ImageField(default='images/avatar/default.png', upload_to='images/avatar/')),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('charm', models.IntegerField(default=0)),
                ('surplus', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodeToItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('explanation', models.CharField(default='Explanation', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(default='Explanation', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CombinationContain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Combination')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(default='static/tycoon/blank.png', upload_to='images/icon/')),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('charm', models.IntegerField(default=0)),
                ('surplus', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='contain',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='contain',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Avatar'),
        ),
        migrations.AddField(
            model_name='combination',
            name='item1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='combination',
            name='item2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='combination',
            name='new_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_item', to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='codetoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='cur_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur_title', to='tycoon.Title'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_list',
            field=models.ManyToManyField(blank=True, db_index=True, to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='title_list',
            field=models.ManyToManyField(blank=True, related_name='title_list', to='tycoon.Title'),
        ),
    ]
