# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(upload_to='tycoon/images/icon/'),
        ),
    ]
