# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0002_avatar_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='chaeyongHi', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='codetoitem',
            name='explanation',
            field=models.CharField(default='Explanation', max_length=40),
        ),
        migrations.AlterField(
            model_name='combination',
            name='explanation',
            field=models.CharField(default='Explanation', max_length=60),
        ),
        migrations.AddField(
            model_name='avatar',
            name='mission_list',
            field=models.ManyToManyField(blank=True, null=True, to='tycoon.Mission'),
        ),
    ]
