# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0003_auto_20170131_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='charm_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combination',
            name='intelligence_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combination',
            name='luck_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combination',
            name='strength_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combination',
            name='surplus_b',
            field=models.IntegerField(default=0),
        ),
    ]
