# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0004_auto_20170131_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='explanation',
            field=models.CharField(default='Make star shape with bunban members finger', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(default='Twinkle Twinkle Little Stars', max_length=60),
        ),
    ]
