# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0004_avatar_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='cur_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tycoon.Title'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='tycoon.Item'),
        ),
    ]
