# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0005_auto_20170110_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='items',
        ),
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(default='chaeyong', max_length=20),
        ),
        migrations.AddField(
            model_name='contain',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycoon.Avatar'),
        ),
    ]
