# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0005_auto_20170131_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetoitem',
            name='code',
            field=models.CharField(max_length=40),
        ),
    ]
