# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0006_auto_20170131_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.BooleanField(default=False),
        ),
    ]
