# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0006_auto_20170111_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetoitem',
            name='explanation',
            field=models.CharField(default='Explanation', max_length=30),
        ),
    ]
