# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0007_codetoitem_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image_b',
            field=models.ImageField(default='images/avatar/default.png', upload_to='images/avatar/'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='image_f',
            field=models.ImageField(default='images/avatar/default.png', upload_to='images/avatar/'),
        ),
    ]
