# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0008_auto_20170111_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='explanation',
            field=models.CharField(default='Explanation', max_length=40),
        ),
    ]
