# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0008_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/map/map.png', upload_to='images/map/')),
            ],
        ),
    ]
