# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0009_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='color',
            field=models.CharField(default='orange', max_length=20),
        ),
    ]
