# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0009_auto_20170118_0044'),
        ('tycoon', '0009_combination_explanation'),
    ]

    operations = [
    ]
