# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0011_auto_20170118_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='title_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='title_list', to='tycoon.Title'),
        ),
    ]
