# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0013_auto_20170118_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='explanation',
        ),
        migrations.AddField(
            model_name='avatar',
            name='item_list',
            field=models.ManyToManyField(blank=True, db_index=True, to='tycoon.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='icon_b',
            field=models.ImageField(default='static/tycoon/blank.png', upload_to='images/icon/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(default='static/tycoon/blank.png', upload_to='images/icon/'),
        ),
    ]
