# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0014_auto_20170121_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='icon_b',
        ),
    ]
