# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoon', '0015_remove_item_icon_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetoitem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
